name: cameroon_hymn
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4
  custom_lint: ^0.5.6
  flutter_riverpod: ^2.4.6
  flutter_dash: ^1.0.0
  svg_flutter: ^0.0.1
  scroll_to_index: ^3.0.1
  path_provider: ^2.1.2
  sembast: ^3.6.0
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  characters: ^1.3.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_core: ^2.30.1
  firebase_remote_config: ^4.4.4
  firebase_analytics: ^10.10.4
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/hymns_json/hymns.json
    - assets/icons/
    - assets/svg/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono-MediumItalic.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/app_icons.png"
  ios: true
  remove_alpha_ios: true
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
